filter:
    paths: [src/*]
    excluded_paths: [client-side/*, tests/*, vendor/*]

before_commands:
    - 'composer install --prefer-source'

tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        excluded_dirs: [client-side, vendor, tests]
    php_cpd:
        excluded_dirs: [client-side, vendor, tests]
    php_analyzer: true

checks:
    php:
        code_rating: true